version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=department_db
    networks:
      - net 

networks:
  net:      
#docker-compose up -d


